@host = http://localhost:5189

# @name create
POST {{host}}/products
Content-Type: application/json

{
    "Name": "MacBook Pro M3 Max",
    "Category": "Electronics",
    "SubCategory": "Laptops"
}

### get based on location header

GET {{create.response.headers.Location}}